M48
; DRILL file {KiCad 7.0.7} date Tue Nov  7 19:32:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-07T19:32:15-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0154
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0181
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0354
%
G90
G05
T1
X3.525Y-2.91
X3.625Y-2.91
T2
X3.234Y-3.396
X3.918Y-3.41
T3
X3.575Y-3.2296
X3.575Y-3.4304
X3.6754Y-3.33
T4
X3.5265Y-2.623
X3.6265Y-2.623
T0
M30
