M48
; DRILL file {KiCad 7.0.7} date Tue Nov  7 19:30:14 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-07T19:30:14-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0181
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.215Y-3.0562
X5.215Y-3.1349
X5.2544Y-3.0956
T2
X5.155Y-3.3006
X5.255Y-3.3006
T0
M30
